# Generated by Django 4.0.6 on 2022-09-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_title', models.CharField(max_length=200)),
                ('Author_name', models.CharField(max_length=200)),
                ('Published_date', models.CharField(max_length=10)),
                ('Blog_detail', models.CharField(max_length=1000)),
                ('Blog_image', models.ImageField(upload_to='blogs')),
            ],
        ),
    ]
