# Generated by Django 4.0.6 on 2022-09-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglist',
            name='Likes',
            field=models.IntegerField(default=0),
        ),
    ]
