# Generated by Django 4.1.5 on 2023-04-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_bloglist_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglist',
            name='Published_date',
            field=models.DateField(max_length=10),
        ),
    ]
