# Generated by Django 4.1.5 on 2023-04-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_bloglist_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglist',
            name='Published_date',
            field=models.DateField(),
        ),
    ]
