# Generated by Django 4.1.5 on 2023-05-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_bloglist_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglist',
            name='Blog_category',
            field=models.CharField(choices=[('option1', 'Business'), ('option2', 'Culture'), ('option3', 'Food'), ('option4', 'Technology'), ('option4', 'Social')], default=0, max_length=500),
        ),
    ]
