# Generated by Django 4.2 on 2023-05-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_alter_bloglist_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglist',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
