# Generated by Django 4.2 on 2023-05-25 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_bloglist_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloglist',
            old_name='likes',
            new_name='add_likes',
        ),
    ]
