# Generated by Django 4.2 on 2023-05-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_rename_add_likes_bloglist_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglist',
            name='Likes',
        ),
    ]
