# Generated by Django 4.1.5 on 2023-06-02 05:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0012_remove_bloglist_likes_bloglist_addlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglist',
            name='Addlikes',
        ),
        migrations.AddField(
            model_name='bloglist',
            name='Addlikes',
            field=models.ManyToManyField(related_name='blog', to=settings.AUTH_USER_MODEL),
        ),
    ]
