# Generated by Django 4.1.5 on 2023-06-02 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0014_remove_bloglist_addlikes_bloglist_dislikes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloglist',
            old_name='likes',
            new_name='Addlikes',
        ),
    ]
