# Generated by Django 4.1.5 on 2023-06-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_rename_likes_bloglist_addlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglist',
            name='dislikes',
        ),
    ]
