# Generated by Django 4.1.5 on 2023-06-02 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0017_blog_likes_remove_bloglist_addlikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_likes',
            old_name='post_id',
            new_name='blog_id',
        ),
    ]
